### ISSUE TITLE
希望：オーストラリア対応

### ISSUE THREAD

**Issue by sina2** [gh640/gcp-block-country-ja#2]
GCP Compute Engine では　中国とオーストラリアの通信費が有料のためブロックしたい。

https://cloud.google.com/free/

**Comment by gh640** [comment]
ありがとうございます。こちらの記述ですね。

> Compute Engine

English:

> 1 GB network egress from North America to all region destinations (excluding China and Australia) per month

日本語:

> 1 GB の北米から全リージョン宛ての下り（外向き）ネットワーク（1 か月あたり、中国とオーストラリアを除く）

https://cloud.google.com/free

**Comment by gh640** [comment]
変更: https://github.com/sina2/gcp-block-country-ja/commit/93e75468752b21f69d545eca3d1e4888ca12a43b

**Comment by gh640** [comment]
@sina2 こちらもいただいたマージリクエストで反映できたので、クローズさせていただきます。ありがとうございました :D
